### ISSUE TITLE
Don't use Flow when not needed

### ISSUE THREAD

**Issue by DenisBronx** [KwabenBerko/Currency-Converter#59]
I see that everything is a `Flow`.
I haven't checked all your use cases but for example `HasCompletedInitialSync` should not return a flow.

The name itself states that you should expect either a single true or false and in the VM you do a `take(1)`.
IMO this should be a suspend fun if not a synchronous function that returns true/false (the latter would be better).

**Comment by KwabenBerko** [comment]
In the Application class, we listen to the changes of this flow to schedule the background SyncWorker

**Comment by DenisBronx** [comment]
gotcha, I missed that
