### ISSUE TITLE
Don't put interface and implementation in the same file

### ISSUE THREAD

**Issue by DenisBronx** [KwabenBerko/Currency-Converter#60]
Abstractions and concretions should never be in the same file, for example, `ConvertMoney` and `RealConvertMoney`.

The reason is that this approach doesn't scale when you have multiple implementations (are you going to have interface and n implementations all the same file? are you going to move the interface out?).
Also it is hard to understand the imports, since now interface and implementation imports are mixed.

My personal preference for use cases:
I usually like to put the use case interfaces all in the same file (`ConverterUseCases`), this way when I open that file I can see all the things the user can do with this module (screaming architecture).

**Comment by KwabenBerko** [comment]
Makes sense. What about an `impl` package containing the implementation for useful usecases? So in this case `RealConvertMoney` will be in the `impl` package. I prefer to have each usecase interface in its own separate file

**Comment by DenisBronx** [comment]
that's perfectly fine!
